version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    # These next lines define a docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to upate the tag on this image to a more stable version, using latest can result in unstable builds.
    docker:
      - image: maven:3.6.3-openjdk-15-slim
    steps:
      # Checkout the code as the first step.
      - checkout
      - run: ls -lah
      - run: mvn --version
      - run:
          # Update this line with the directory that contains your tests project file
          working_directory: ~
          name: Install dependencies
          command: |
            mvn -B -DskipTests clean package

