version: 2.1
jobs:
  build:
    docker:
      - image: openjdk
    steps:
      - checkout
      - run: ls -lah
      - run: 
        working_directory: ~/project/src
        name: Install dependencies
        command: mvn install
docker-lint:
  docker:
    - image: hadolint/hadolint
  steps:
    - checkout
    - run: ls ~/project/src -lah
    - run:
      working_directory: ~/project/src
      name: Run hadolint
      command: |
        hadolint Dockerfile
workflows:
  build:
    jobs:
       - build
       - docker-lint:
         requires:
          - build
      
