version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
jobs:
  build:
    docker:
      - image: maven:3.6.3-openjdk-15-slim
    steps:
      - checkout
      - run: ls -lah
      - run: mvn --version
      - run:
          working_directory: ~
          name: Install dependencies
          command: |
            mvn -B -DskipTests clean package

